version: "3"
services:
  scoring-module:
    image: apastor/nameles-scoring-module
    networks:
      nameles-net:
        ipv4_address:  172.20.0.129
    restart: "no"
    expose:
      - "58520"
    environment:
      - DSP_IP=172.20.0.130
      - FWD_PORT=58510 # 0 for not forwarding when not using the streaming module.
      - RCV_PORT=58501
      - SND_PORT=58505
      - DB_IP=172.20.0.128
      - DB_USER=nameles
      - DB_PWD=""
      - DB_NAME=nameles
      - WORKERS=2
      - MIN_TOTAL=250

networks:
  nameles-net:
    external: true
